spring.application.name=tracknest
spring.datasource.url=jdbc:mysql://localhost:3306/tracknest
spring.datasource.username=root
spring.datasource.password=Evy@3112

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080
